-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsCZYXg/iMvTINaj6
8uAaJvCEzyjCQEAiLyDniCAQPlegCgYIKoZIzj0DAQehRANCAAQLgswU/MHG6qlb
ODty5wS7uyCIPuARA3IDoaQjJLR2FX8CGjr38QA/cl+g/9XxPYH65cf+rs1blppt
FK3FKsNM
-----END PRIVATE KEY-----